import sys
from core.database import DeltaDB
from modules.recon import ReconEngine
from modules.prober import LiveProber
from modules.js_analyzer import JSAnalyzer

def main():
    target_domain = sys.argv[1] if len(sys.argv) > 1 else "testfire.net"
    
    db = DeltaDB()
    domain_id = db.add_domain(target_domain)
    
    print(f"\n[*] Target: {target_domain} (ID: {domain_id})")
    print("[*] Phase 1: Gathering passive intelligence...")

    engine = ReconEngine(target_domain)
    discovered_assets = engine.run_all()

    new_assets_to_probe = {}

    print("\n[*] Phase 2: Evaluating Deltas...")
    with db._get_connection() as conn:
        cursor = conn.cursor()
        for sub in discovered_assets:
            cursor.execute('SELECT id FROM subdomains WHERE subdomain = ?', (sub,))
            result = cursor.fetchone()
            
            if not result:
                cursor.execute('INSERT INTO subdomains (domain_id, subdomain) VALUES (?, ?)', (domain_id, sub))
                new_id = cursor.lastrowid
                new_assets_to_probe[new_id] = sub
                print(f"[+] NEW DELTA: {sub}")
            else:
                cursor.execute('UPDATE subdomains SET last_seen = CURRENT_TIMESTAMP WHERE id = ?', (result[0],))

    print(f"\n[+] Found {len(new_assets_to_probe)} brand-new assets.")

    if new_assets_to_probe:
        print("\n[*] Phase 3: Launching Live Prober on Delta Assets...")
        prober = LiveProber(threads=20)
        live_services = prober.run(new_assets_to_probe)

        print("\n[*] Phase 4: Committing verified web services & extracting JS Intel...")
        for service in live_services:
            db.add_web_service(
                subdomain_id=service["subdomain_id"],
                url=service["url"],
                status_code=service["status_code"],
                content_length=service["content_length"],
                title=service["title"]
            )
            
            # Retrieve the web service ID generated by SQLite to match dependencies
            with db._get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute('SELECT id FROM web_services WHERE url = ?', (service["url"],))
                service_id = cursor.fetchone()[0]

            # Trigger JS Analysis on the newly verified live application URL
            print(f"    └── Parsing scripts on {service['url']}...")
            analyzer = JSAnalyzer(service["url"])
            intel = analyzer.analyze()

            # Record internal architectural endpoints found
            if intel["paths"]:
                print(f"        [+] Found {len(intel['paths'])} distinct client-side endpoints/routes.")
                for path in intel["paths"]:
                    db.add_endpoint(web_service_id=service_id, path=path, source="js_analyzer")

            # Record high-entropy tokens or configurations leaked
            if intel["secrets"]:
                print(f"        [!] CRITICAL: Found {len(intel['secrets'])} potential hardcoded credentials/tokens!")
                for secret in intel["secrets"]:
                    db.add_secret(
                        web_service_id=service_id,
                        secret_type=secret["type"],
                        value=secret["value"],
                        location=secret["location"]
                    )

            db.mark_scanned(service["subdomain_id"])
        
        print(f"\n[+] Processing complete. Attack surface data fully structured inside data/uro.db")
    else:
        print("\n[*] No new assets require probing or static code analysis.")

if __name__ == "__main__":
    main()